################################################################################
# CAR-T: Given a directory where LMR files generated by getLMRpercs.R are,     #
# integrates all of them into a single matrix with methylation percentage per  #
# LMR on each sample (CSV).                                                    #
################################################################################

if(!require("argparser", quietly = T)){
        install.packages("argparser",
        repos = "https://pbil.univ-lyon1.fr/CRAN/")
}

# Parser
################################################################################
parser <- arg_parser("Given a directory where LMR files generated by getLMRpercs are,
integrates all of them into a single matrix with methylation percentage per
LMR on each sample (CSV).")

parser <- add_argument(parser = parser,
                       arg = c("input",
                               "--outTag",
                               "--outDir"),
                       help = c("Directory where files generated by getLMRpercs.R are.",
                                "Name to be included in the file name as a tag.",
                                "Output directory."),
                       flag = c(F, F, F))

parsed <- parse_args(parser)

# Functions
################################################################################

# Read csv faster
readCsvFast <- function(f){
        df <- data.frame(data.table::fread(f))
        rownames(df) <- df$V1
        df <- df[, colnames(df) != "V1"]
        return(df)
}

# write.csv, but faster
writeCsvFst <- function(df, file, rowNames = T, colNames = T){
        if(rowNames){
                rn <- rownames(df)
                df <- data.table::data.table(df)
                df[, V1 := rn]
                data.table::setcolorder(df, c("V1", setdiff(names(df), "V1")))
        }else{
                df <- data.table::data.table(df)
        }
        data.table::fwrite(df, file, col.names = colNames)
}

# Add a / if it's not at the end of a directory string
addSlashIfNot <- function(pth){
        lastChar <- substr(pth, nchar(pth), nchar(pth))
        if(lastChar != "/"){
                pth <- paste0(pth, "/")
        }
        return(pth)
}

# Create directory if it doesn't exist
createIfNot <- function(pth){
        if(!dir.exists(pth)){
                dir.create(pth, recursive = T)
        }
}

# Directory stuff
################################################################################
lmrDir <- addSlashIfNot(parsed$input)
outTag <- parsed$outTag
outDir <- addSlashIfNot(parsed$outDir)

createIfNot(outDir)

# Combine files into a single CSV file
################################################################################
lmrFiles <- list.files(lmrDir, full.names = T)
# Remove combined file, if it's there
lmrFiles <- lmrFiles[!grepl("lmrComb.csv", lmrFiles)]

lmrMethMat <- list()
pb <- txtProgressBar(min = 0, max = length(lmrFiles), initial = 0, style = 3)
for(i in seq_along(lmrFiles)){
        setTxtProgressBar(pb, i)
        f <- lmrFiles[i]
        samp <- basename(f)
        samp <- gsub("_LMRs.csv", "", samp)

        lmr <- readCsvFast(f)

        percMethVec <- lmr$percMethAll
        lmrNames <- paste(lmr$chr,
                          paste(lmr$start,
                                lmr$end,
                                sep = "_"),
                          sep = ".")
        toBind <- data.frame(matrix(percMethVec,
                                    nrow = 1,
                                    ncol = length(percMethVec),
                                    dimnames = list(samp, lmrNames)))
        lmrMethMat[[samp]] <- toBind
}

lmrMethMat <- do.call(rbind, lmrMethMat)

outName <- sprintf("%s%s_lmrComb.csv", outDir, outTag)

writeCsvFst(lmrMethMat, file = outName)
print(sprintf("%s saved at %s.", basename(outName), dirname(outName)))